spring:
  docker:
    compose:
      file: src/main/docker/compose.yaml
      enabled: true
      lifecycle-management: start_only
  jpa:
    properties:
      hibernate:
        default_schema: public

  liquibase:
    change-log: db/changelog/master.yaml
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/x-leagues
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

server:
  port: 8081

jwt:
  auth:
    converter:
      resource-id: nabil-rest-api
      principle-attribute: preferred_username



